name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: mingw-w64 gcc-mingw-w64-x86-64
        version: 1.0
    - name: make-linux
      run: make linux
    - name: make-linux-omp
      run: make linux-omp
    - name: make-windows
      run: make windows
    - name: make-windows-omp
      run: make windows-omp
      
