name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install-mingw
      run: sudo apt install -y gcc-mingw-w64-x86-64
    - name: make-linux
      run: make linux
    - name: make-linux-omp
      run: make linux-omp
    - name: make-windows
      run: make windows
    - name: make-windows-omp
      run: make windows-omp
      
